### ISSUE TITLE
Repository clone Issue

### ISSUE THREAD

**Issue by riyakushwaha** [abhpd/hacktoberfest2021#308] opened 2021-10-01 13:49 UTC
On cloning the unsder mentioned error is coming on Windows

error: invalid path 'C++/Problems/backtracking/A*_weels.cpp'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by abhpd** [comment] 2021-10-01 14:20
I'll check.

**Comment by abhpd** [comment] 2021-10-01 14:24
@riyakushwaha Cloning is working fine on my end, can you please recheck or maybe share some screenshots of what you're trying to do.

**Comment by adarsh786-tech** [comment] 2021-10-01 14:40
@abhpd even I am facing the same issue. I am unable to clone the forked repository. I am attaching the screenshot of the issue
![git repo clone issue](https://user-images.githubusercontent.com/52563368/135638767-5117bd83-5580-46d4-ad66-127901cb036e.PNG)
.

**Comment by abhpd** [comment] 2021-10-01 14:42
@adarsh786-tech  I think the problem is with the filename. I'll Commit a change let me know if it works afterward.

**Comment by abhpd** [comment] 2021-10-01 14:46
@adarsh786-tech and @riyakushwaha It should be fixed now, Please check.

**Comment by adarsh786-tech** [comment] 2021-10-01 14:56
@abhpd yes, it is working perfectly fine. Thankyou

**Closed** 2021-10-01 14:57 UTC
